### ISSUE TITLE
Bibox unhandled exception failures

### ISSUE THREAD

**Issue by bmancini55** [altangent/ccxws#107]
**Exchange**
Bibox

**Subscription type**
Any

**Describe the bug**
Refer to error below:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: '3009', msg: '推送订阅channel不合法' })
    at BiboxBasicClient.emit (events.js:187:17)
    at BiboxBasicClient._processsMessage (/usr/src/app/orderbook/orderbook-feed/node_modules/ccxws/src/exchanges/bibox-client.js:321:12)
    at BiboxBasicClient._onMessage (/usr/src/app/orderbook/orderbook-feed/node_modules/ccxws/src/exchanges/bibox-client.js:289:12)
    at SmartWss._wss.on.msg (/usr/src/app/orderbook/orderbook-feed/node_modules/ccxws/src/basic-client.js:176:16)
    at SmartWss.emit (events.js:198:13)
    at WebSocket._wss.on.msg (/usr/src/app/orderbook/orderbook-feed/node_modules/ccxws/src/smart-wss.js:75:43)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/usr/src/app/orderbook/orderbook-feed/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/usr/src/app/orderbook/orderbook-feed/node_modules/ws/lib/receiver.js:422:14)
Emitted 'error' event at:
    at BiboxBasicClient._onError (/usr/src/app/orderbook/orderbook-feed/node_modules/ccxws/src/basic-client.js:191:10)
    at SmartWss._wss.on.msg (/usr/src/app/orderbook/orderbook-feed/node_modules/ccxws/src/basic-client.js:178:16)
    at SmartWss.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at Receiver.dataMessage (/usr/src/app/orderbook/orderbook-feed/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/usr/src/app/orderbook/orderbook-feed/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/usr/src/app/orderbook/orderbook-feed/node_modules/ws/lib/receiver.js:138:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @blocktap/orderbook@1.0.0 feed: `cd orderbook-feed; node src "Bibox" "--engine=10.0.10.151:10026"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @blocktap/orderbook@1.0.0 feed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-24T19_56_33_060Z-debug.log
```
**To Reproduce**
Subscribe to an invalid market

**Expected behavior**
Error message emitted but process does not stop

**Comment by bmancini55** [comment]
Fixed in be275a0957f1d0a3a9beab9a9337b415dfb1caca
