### ISSUE TITLE
error handler

### ISSUE THREAD

**Issue by pro-git** [altangent/ccxws#274]
Seem that I can't install a error handler for each exchange, there is only one for all of them.
If I use multiple exchanges, only the last one is firing for errors from all exchanges.
So, how can I find the source of this error (exchange)?

Error: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>

    at IncomingMessage.<anonymous> (/projects/ccxwscode/node_modules/ccxws/src/https.js:37:25)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by bmancini55** [comment]
Thanks for submitting the issue! Can you provide example code of how you're attaching the error handler to each client?

**Comment by bmancini55** [comment]
Error events currently do not include the name of the exchange or client scope of the error.   There is an item #104 that tracks improving error handling.  That covers both this type of error (additional information about errors) as well as tracking subscription failures.  Unfortunately the library doesn't support a great way to detect subscription errors.

**Comment by pro-git** [comment]
Including name of the exchange in error events and disconnect/reconnecting/connected events at least should be easy.

**Comment by bmancini55** [comment]
In the example code you posted your exchange is closure scoped.  You can just reference the exchange in the error handler event. 

```javascript
ccxwsArray[exchange].on("error", err => console.error(chalk.red("error: ")+exchange+("%s"), err));
```
Alternative you could use a curry if you have a more complicated construct:

```
const errorHandler = function (exchange) {
    return err => console.error(chalk.red("error: ")+exchange+(" %s"), err)
}

ccxwsArray[exchange].on("error", errorHandler(exchange));
```

**Comment by pro-git** [comment]
that was what I did initially 
```
ccxwsArray[exchange].on("error", err => console.error(chalk.red("%s: ")+("%s"), exchange, err));
```
but the error is always firing with the name of the last exchange in array.

**Comment by pro-git** [comment]
solved.
using exchanges.forEach(myFunction) instead of "for" loop.

**Comment by bmancini55** [comment]
Nice! I think you could have also changed the `var` to `let` or `const` so that variable doesn't get hoisted. 

```
const exchange = exchanges[i]
```
 Since it gets hoisted it breaks the closure usage. For `forEach` it scopes to the function, so the hoisting has no effect.

**Comment by pro-git** [comment]
I got printed to console "warn: failure response {"event":"error","message":"Channel spot/depth_l2_tbt:ETHUSDT doesn't exist","errorCode":30040}" even without error handler.
How can I find the source of the message? (exchange). This error shouldn't go trough the Error handler?

Also, I didn't get any l2updates from any exchange and after less than a minute all of the get disconnected & reconnect.
BTW, there is a automatic re-subscription on reconnect?

**Comment by bmancini55** [comment]
Looks like it's from okex.  Some of the older clients don't emit errors and just log warnings.  That needs to be fixed.

**Comment by pro-git** [comment]
Any ideea why I'm not receiving any data from any exchange?

using 
```
const market1 = {
  id: "ETHUSDT", // remote_id used by the exchange
  base: "ETH",  // standardized base symbol for Bitcoin
  quote: "USDT", // standardized quote symbol for Tether
};
      ccxwsArray[exchange].on("l2updates", updates => console.log("%s", updates));
      ccxwsArray[exchange].subscribeLevel2Updates(market1);
      ccxwsArray[exchange].on("l2snapshots", snapshots => console.log("%s", snapshots));
      ccxwsArray[exchange].subscribeLevel2Snapshots(market1);
```

**Comment by bmancini55** [comment]
Possibly that market id is unique to exchanges.  Make sure you use the correct id for each exchange even if it's the same base and quote pair as other exchanges.
