### ISSUE TITLE
kucoin market issue

### ISSUE THREAD

**Issue by myehrajat** [altangent/ccxws#333]
in kucoin this format work properly please fix it to a unified format
const market = {
    id: "BTC-USDT", // remote_id used by the exchange
    base: "BTC", // standardized base symbol for Bitcoin
    quote: "USDT", // standardized quote symbol for Tether
};

**Comment by myehrajat** [comment]
Error: topic /market/match:BTCUSDT is not found
    at KucoinClient._processMessage (D:\nodejs\MyProject\node_modules\ccxws\dist\src\exchanges\KucoinClient.js:271:25)
    at KucoinClient._onMessage (D:\nodejs\MyProject\node_modules\ccxws\dist\src\exchanges\KucoinClient.js:259:22)
    at SmartWss.<anonymous> (D:\nodejs\MyProject\node_modules\ccxws\dist\src\exchanges\KucoinClient.js:146:22)
    at SmartWss.emit (node:events:390:28)
    at WebSocket.<anonymous> (D:\nodejs\MyProject\node_modules\ccxws\dist\src\SmartWss.js:83:49)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (D:\nodejs\MyProject\node_modules\ws\lib\websocket.js:1068:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (D:\nodejs\MyProject\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (D:\nodejs\MyProject\node_modules\ws\lib\receiver.js:435:17)
Emitted 'error' event on KucoinClient instance at:
    at KucoinClient._onError (D:\nodejs\MyProject\node_modules\ccxws\dist\src\BasicClient.js:202:14)
    at SmartWss.<anonymous> (D:\nodejs\MyProject\node_modules\ccxws\dist\src\exchanges\KucoinClient.js:149:22)
    at SmartWss.emit (node:events:390:28)
    [... lines matching original stack trace ...]
    at Receiver.getData (D:\nodejs\MyProject\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (D:\nodejs\MyProject\node_modules\ws\lib\receiver.js:143:22) {
  msg: {
    id: '1659816801999',
    type: 'error',
    code: '404',
    data: 'topic /market/match:BTCUSDT is not found'
  }
}
